Rsapi v1.2.0 -- rebase influitive/apartment v1.2.0
retentionscience/apartment pull request #7
Opened 2017-11-07 22:55 UTC by rs-longsheng

2017-11-21 00:12 UTC, rs-longsheng commented on lib/apartment/adapters/abstract_adapter.rb
> +        unenvironmentify(Apartment.connection.current_database)
Tenant name should be "site_152", instead of "development_site_152". Rsapi production should not be affected tho.

2017-11-21 00:40 UTC, rs-longsheng commented on lib/apartment/adapters/mysql2_adapter.rb
> +        if server_changed?(tenant)
kinda speed up. only create a new connection pool if server changed (host changed).

2017-11-21 23:04 UTC, awaage requested changes

2017-11-21 23:04 UTC, awaage commented on lib/apartment/adapters/abstract_adapter.rb
> +            tenant.gsub(/^_#{Rails.env}$/, "")
this regex looks wrong. 
I think you want to remove the "^" symbol

2017-11-21 23:04 UTC, awaage commented on lib/apartment/adapters/mysql2_adapter.rb
> +            Apartment.connection.execute "use `#{Apartment::Tenant.current}`"
why do you need to do this line 28?

2017-11-21 23:35 UTC, rs-longsheng commented on lib/apartment/adapters/abstract_adapter.rb
> +        unenvironmentify(Apartment.connection.current_database)
Known issue https://github.com/influitive/apartment/issues/465

2017-11-21 23:41 UTC, rs-longsheng commented
@awaage fixed.

2017-11-22 23:39 UTC, awaage approved these changes
lgtm

2017-11-22 23:42 UTC, awaage commented
Are migrations handled automatically still? Apt will be smart enough to switch to all hosts and run migrations ?

2017-11-28 23:16 UTC, rs-longsheng commented
@awaage yes

2017-12-15 19:35 UTC, awaage commented
not need to be merged. closing PR

2017-12-15 19:35 UTC, closed without merging